package com.mkdevelopment.myaccounts.common

import androidx.annotation.DrawableRes
import com.mkdevelopment.myaccounts.R

class IconHelper {
    companion object {
        val iconList = listOf(
            R.drawable.ic_ui_user,
            R.drawable.ic_ui_sms,
            R.drawable.ic_ui_location,
            R.drawable.password_toggle_drawable,
            R.drawable.ic_adobe,
            R.drawable.ic_apple,
            R.drawable.ic_apple_music,
            R.drawable.ic_battle_net,
            R.drawable.ic_behance,
            R.drawable.ic_behance_only,
            R.drawable.ic_creative_cloud,
            R.drawable.ic_devianart,
            R.drawable.ic_discord,
            R.drawable.ic_discord_full,
            R.drawable.ic_dribbble,
            R.drawable.ic_dribbble_colored,
            R.drawable.ic_dribbble_white,
            R.drawable.ic_drive,
            R.drawable.ic_dropbox,
            R.drawable.ic_electronic_arts,
            R.drawable.ic_facebook_2023,
            R.drawable.ic_facebook_brand_2023,
            R.drawable.ic_facebook_messenger_2013,
            R.drawable.ic_facebook_messenger_2020,
            R.drawable.ic_figma,
            R.drawable.ic_fiverr,
            R.drawable.ic_github,
            R.drawable.ic_github_v2,
            R.drawable.ic_gmail,
            R.drawable.ic_google_play,
            R.drawable.ic_hbo,
            R.drawable.ic_imdb,
            R.drawable.ic_instagram_icon,
            R.drawable.ic_instagram_2022,
            R.drawable.ic_instagram_black_2022,
            R.drawable.ic_instagram_white_line,
            R.drawable.ic_line,
            R.drawable.ic_linkedin,
            R.drawable.ic_linkedin_circle,
            R.drawable.ic_mailchimp,
            R.drawable.ic_mastercard,
            R.drawable.ic_medium,
            R.drawable.ic_medium_circle,
            R.drawable.ic_messenger_original,
            R.drawable.ic_messenger_white,
            R.drawable.ic_microsoft,
            R.drawable.ic_netflix,
            R.drawable.ic_notion,
            R.drawable.ic_paypal,
            R.drawable.ic_pinterest,
            R.drawable.ic_quora,
            R.drawable.ic_reddit,
            R.drawable.ic_reddit_circle,
            R.drawable.ic_reddit_v2,
            R.drawable.ic_shutterstock,
            R.drawable.ic_signal,
            R.drawable.ic_skype,
            R.drawable.ic_snapchat,
            R.drawable.ic_snapchat_yellow_circle,
            R.drawable.ic_sound_cloud_circle,
            R.drawable.ic_soundcloud,
            R.drawable.ic_spotify,
            R.drawable.ic_telegram,
            R.drawable.ic_telegram_only,
            R.drawable.ic_threads_black_line,
            R.drawable.ic_threads_full,
            R.drawable.ic_threads_line_gradient,
            R.drawable.ic_tiktok,
            R.drawable.ic_tumblr,
            R.drawable.ic_tumblr_circle,
            R.drawable.ic_twitch,
            R.drawable.ic_twitter,
            R.drawable.ic_viber,
            R.drawable.ic_vimeo,
            R.drawable.ic_visa,
            R.drawable.ic_vk,
            R.drawable.ic_vk_only,
            R.drawable.ic_wechat,
            R.drawable.ic_whatsapp,
            R.drawable.ic_whatsapp_white_line,
            R.drawable.ic_x_twitter,
            R.drawable.ic_youtube,
            R.drawable.ic_youtube_circle,
            R.drawable.ic_youtube_music,
            R.drawable.ic_zoom
        )
        fun getIconByPosition(position: Int): Int {
            return iconList[position]
        }
    }
}
